name: GitHubPages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.1]

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Install and build
        working-directory: ./frontend
        run: npm install && npm run build:prod-github && cp dist/frontend/index.html

      - name: Deploy
        uses: chavdarovae/github-pages-deploy-action@4.1.1
        with:
          branch: gh-branches
          folder: workoutApp/dist/frontend
