name: GitHubPages Deploy

on:
  push:
    branches:
      - "main"
    # paths:
    #   - 'apps/firstApp/**'

env:
  BEFORE_SHA: ${{ github.event.before }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.1]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          # Required by nrwl/nx-set-shas
          fetch-depth: 0

      - name: 'Derive appropriate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v2

      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Install dependencies
        run: echo "Installing" && npm install --force

      - name: Build
        # run: echo "Building" && npm run build:prod:affected  -- --base=remotes/origin/main
        run: echo "Building" && npm run build:prod:affected --base=origin/main --head=HEAD

      - name: List Files in Root Directory
        run: ls -Rd */

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-branches
          folder: dist/apps/firstApp
