name: GitHubPages Deploy

on:
  push:
    branches:
      - "main"
    # paths:
    #   - 'apps/firstApp/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.1]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: echo "Installing" && npm install --force

      - name: Build
        run: echo "Building" && npm install --force && npm run build:prod:firstApp

      - name: List Files in Root Directory
        run: |
          cd dist
          ls -R

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-branches
          folder: dist/apps/firstApp
